# change 'edu_project_template' everywhere it appears in this document 
# to match your project's name
name: 'edu_project_template'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'edu_project_template'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-end: "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"

models:
  edu_wh:
    +materialized: table
    build:
      +schema: build
    core_warehouse:
      +schema: wh
  dbt_artifacts:
    +schema: dbt_run__audit
    +tags: ['bypass_rls']

vars:

  # labels for generated race/ethnicity groups
  'edu:stu_demos:multiple_races_code': Multiple
  'edu:stu_demos:hispanic_latino_code': Latinx
  'edu:stu_demos:race_unknown_code': Unknown
  
  'edu:candidate_demos:multiple_races_code': Multiple
  'edu:candidate_demos:hispanic_latino_code': Latinx
  'edu:candidate_demos:race_unknown_code': Unknown

  # rules for inclusion in 'special education' demographic group
  # Begin and end dates to use for cutoffs, and a list of program names to exclude
  'edu:special_ed:start_date_column': program_enroll_begin_date
  'edu:special_ed:exit_date_column': program_enroll_end_date
  'edu:special_ed:exclude_programs': Null

  # label for 'Present' days generated from negative attendance
  'edu:attendance:in_attendance_code': In Attendance
  # threshold and minimum enrolled days for chronic absence definition
  'edu:attendance:chronic_absence_threshold': 90
  'edu:attendance:chronic_absence_min_days': 20

  # withdraw codes that should exclude students from enrollment altogether
  'edu:enroll:exclude_withdraw_codes': ['No show', 'Invalid enrollment']
  
  # student discipline participation codes that map to non-offenders
  'edu:discipline:non_offender_codes': ['Victim', 'Witness', 'Reporter']

  # source config
  extensions: null
  
   # Enable optional domains and programs
  'src:domain:assessment:enabled': False
  'src:domain:discipline:enabled': True
  'src:program:special_ed:enabled': False
  'src:program:homeless:enabled': False
  'src:program:language_instruction:enabled': False
  'src:program:title_i:enabled': False
  'src:program:migrant_education:enabled': False
  'src:program:cte:enabled': False
  'src:program:food_service:enabled': False

seeds:
  +schema: seed
  +quote_columns: false
