academicWeeks: 'School Calendar Domain'
accounts: 'Finance Domain'
accountCodes: 'Finance Domain'
accountabilityRatings: 'Enrollment Domain'
actuals: 'Finance Domain'
assessments: 'Assessment Domain'
assessmentItems: 'Assessment Domain'
assessmentScoreRangeLearningStandards: 'Assessment Domain'
bellSchedules: 'Bell Schedule Domain'
budgets: 'Finance Domain'
calendars: 'School Calendar Domain'
calendarDates: 'School Calendar Domain'
classPeriods: 'Bell Schedule Domain'
cohorts: 'Student Cohort Domain'
communityOrganizations: 'Education Organization Domain'
communityProviders: 'Education Organization Domain'
communityProviderLicenses: 'Education Organization Domain'
competencyObjectives: 'Student Academic Record Domain'
contractedStaffs: 'Finance Domain'
courses: 'Teaching and Learning Domain'
courseOfferings: 'Teaching and Learning Domain'
courseTranscripts: 'Student Academic Record Domain'
credentials: 'Staff Domain Domain'
disciplineActions: 'Discipline Domain'
disciplineIncidents: 'Discipline Domain'
educationContents: 'Intervention Domain'
educationOrganizationInterventionPrescriptionAssociations: 'Intervention Domain'
educationOrganizationNetworks: 'Education Organization Domain'
educationOrganizationNetworkAssociations: 'Education Organization Domain'
educationOrganizationPeerAssociations: 'Education Organization Domain'
educationServiceCenters: 'Education Organization Domain'
feederSchoolAssociations: 'Education Organization Domain'
grades: 'Student Academic Record Domain'
gradebookEntries: 'Student Academic Record Domain'
gradingPeriods: 'School Calendar Domain'
graduationPlans: 'Graduation Domain'
interventions: 'Intervention Domain'
interventionPrescriptions: 'Intervention Domain'
interventionStudies: 'Intervention Domain'
learningObjectives: 'Assessment Domain'
learningStandards: 'Assessment Domain'
learningStandardEquivalenceAssociations: 'Assessment Domain'
localEducationAgencies: 'Education Organization Domain'
locations: 'Teaching and Learning Domain'
objectiveAssessments: 'Assessment Domain'
openStaffPositions: 'Staff Domain Domain'
organizationDepartments: 'Education Organization Domain'
parents: 'Student Identification and Demographics Domain'
payrolls: 'Finance Domain'
people: 'Staff Domain Domain'
postSecondaryEvents: 'Graduation Domain'
postSecondaryInstitutions: 'Graduation Domain'
programs: 'Cross-Domain'
reportCards: 'Student Academic Record Domain'
restraintEvents: 'Discipline Domain'
schools: 'Cross-Domain'
schoolYearTypes: 'School Calendar Domain'
sections: 'Cross-Domain'
sectionAttendanceTakenEvents: 'Student Attendance Domain'
sessions: 'Cross-Domain'
staffs: 'Cross-Domain'
staffAbsenceEvents: 'Staff Domain Domain'
staffCohortAssociations: 'Student Cohort Domain'
staffDisciplineIncidentAssociations: 'Discipline Domain'
staffEducationOrganizationAssignmentAssociations: 'Staff Domain Domain'
staffEducationOrganizationContactAssociations: 'Staff Domain Domain'
staffEducationOrganizationEmploymentAssociations: 'Staff Domain Domain'
staffLeaves: 'Staff Domain Domain'
staffProgramAssociations: 'Teaching and Learning Domain'
staffSchoolAssociations: 'Staff Domain Domain'
staffSectionAssociations: 'Staff Domain Domain'
stateEducationAgencies: 'Staff Domain Domain'
students: 'Cross-Domain'
studentAcademicRecords: 'Student Academic Record Domain'
studentAssessments: 'Assessment Domain'
studentCTEProgramAssociations: 'Alternative and Supplemental Services Domain'
studentCohortAssociations: 'Student Cohort Domain'
studentCompetencyObjectives: 'Student Academic Record Domain'
studentDisciplineIncidentAssociations: 'Discipline Domain'
studentDisciplineIncidentBehaviorAssociations: 'Discipline Domain'
studentDisciplineIncidentNonOffenderAssociations: 'Discipline Domain'
studentEducationOrganizationAssociations: 'Enrollment Domain'
studentEducationOrganizationResponsibilityAssociations: 'Enrollment Domain'
studentGradebookEntries: 'Student Academic Record Domain'
studentHomelessProgramAssociations: 'Alternative and Supplemental Services Domain'
studentInterventionAssociations: 'Intervention Domain'
studentInterventionAttendanceEvents: 'Intervention Domain'
studentLanguageInstructionProgramAssociations: 'Alternative and Supplemental Services Domain'
studentLearningObjectives: 'Student Academic Record Domain'
studentMigrantEducationProgramAssociations: 'Alternative and Supplemental Services Domain'
studentNeglectedOrDelinquentProgramAssociations: 'Alternative and Supplemental Services Domain'
studentParentAssociations: 'Student Identification and Demographics Domain'
studentProgramAssociations: 'Teaching and Learning Domain'
studentProgramAttendanceEvents: 'Student Attendance Domain'
studentSchoolAssociations: 'Teaching and Learning Domain'
studentSchoolAttendanceEvents: 'Student Attendance Domain'
studentSchoolFoodServiceProgramAssociations: 'Alternative and Supplemental Services Domain'
studentSectionAssociations: 'Teaching and Learning Domain'
studentSectionAttendanceEvents: 'Student Attendance Domain'
studentSpecialEducationProgramAssociations: 'Alternative and Supplemental Services Domain'
studentTitleIPartAProgramAssociations: 'Alternative and Supplemental Services Domain'
surveys: 'Survey Domain'
surveyCourseAssociations: 'Survey Domain'
surveyProgramAssociations: 'Survey Domain'
surveyQuestions: 'Survey Domain'
surveyQuestionResponses: 'Survey Domain'
surveyResponses: 'Survey Domain'
surveyResponseEducationOrganizationTargetAssociations: 'Survey Domain'
surveyResponseStaffTargetAssociations: 'Survey Domain'
surveySections: 'Survey Domain'
surveySectionAssociations: 'Survey Domain'
surveySectionResponses: 'Survey Domain'
surveySectionResponseEducationOrganizationTargetAssociations: 'Survey Domain'
surveySectionResponseStaffTargetAssociations: 'Survey Domain'

absenceEventCategoryDescriptors: 'Staff Domain Domain'
academicHonorCategoryDescriptors: 'Student Academic Record Domain'
academicSubjectDescriptors: 'Cross-Domain'
accommodationDescriptors: 'Assessment Domain'
accountClassificationDescriptors: 'Finance Domain'
achievementCategoryDescriptors: 'Student Academic Record Domain'
additionalCreditTypeDescriptors: 'Student Academic Record Domain'
addressTypeDescriptors: 'Cross-Domain'
administrationEnvironmentDescriptors: 'Assessment Domain'
administrativeFundingControlDescriptors: 'Education Organization Domain'
ancestryEthnicOriginDescriptors: 'Student Identification and Demographics Domain'
assessmentCategoryDescriptors: 'Assessment Domain'
assessmentIdentificationSystemDescriptors: 'Assessment Domain'
assessmentItemCategoryDescriptors: 'Assessment Domain'
assessmentItemResultDescriptors: 'Assessment Domain'
assessmentPeriodDescriptors: 'Assessment Domain'
assessmentReportingMethodDescriptors: 'Assessment Domain'
attemptStatusDescriptors: 'Teaching and Learning Domain'
attendanceEventCategoryDescriptors: 'Student Attendance Domain'
behaviorDescriptors: 'Discipline Domain'
cteProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
calendarEventDescriptors: 'School Calendar Domain'
calendarTypeDescriptors: 'School Calendar Domain'
careerPathwayDescriptors: 'Teaching and Learning Domain'
charterApprovalAgencyTypeDescriptors: 'Education Organization Domain'
charterStatusDescriptors: 'Education Organization Domain'
citizenshipStatusDescriptors: 'Student Identification and Demographics Domain'
classroomPositionDescriptors: 'Teaching and Learning Domain'
cohortScopeDescriptors: 'Student Cohort Domain'
cohortTypeDescriptors: 'Student Cohort Domain'
cohortYearTypeDescriptors: 'Enrollment Domain'
competencyLevelDescriptors: 'Student Academic Record Domain'
contactTypeDescriptors: 'Student Academic Record Domain'
contentClassDescriptors: 'Teaching and Learning Domain'
continuationOfServicesReasonDescriptors: 'Alternative and Supplemental Services Domain'
costRateDescriptors: 'Finance Domain'
countryDescriptors: 'Cross-Domain'
courseAttemptResultDescriptors: 'Student Academic Record Domain'
courseDefinedByDescriptors: 'Teaching and Learning Domain'
courseGPAApplicabilityDescriptors: 'Teaching and Learning Domain'
courseIdentificationSystemDescriptors: 'Teaching and Learning Domain'
courseLevelCharacteristicDescriptors: 'Teaching and Learning Domain'
courseRepeatCodeDescriptors: 'Student Academic Record Domain'
credentialFieldDescriptors: 'Staff Domain Domain'
credentialTypeDescriptors: 'Staff Domain Domain'
creditCategoryDescriptors: 'Student Academic Record Domain'
creditTypeDescriptors: 'Student Academic Record Domain'
curriculumUsedDescriptors: 'Teaching and Learning Domain'
deliveryMethodDescriptors: 'Intervention Domain'
diagnosisDescriptors: 'Intervention Domain'
diplomaLevelDescriptors: 'Student Academic Record Domain'
diplomaTypeDescriptors: 'Student Academic Record Domain'
disabilityDescriptors: 'Alternative and Supplemental Services Domain'
disabilityDesignationDescriptors: 'Alternative and Supplemental Services Domain'
disabilityDeterminationSourceTypeDescriptors: 'Alternative and Supplemental Services Domain'
disciplineActionLengthDifferenceReasonDescriptors: 'Discipline Domain'
disciplineDescriptors: 'Discipline Domain'
disciplineIncidentParticipationCodeDescriptors: 'Discipline Domain'
educationOrganizationCategoryDescriptors: 'Education Organization Domain'
educationOrganizationIdentificationSystemDescriptors: 'Education Organization Domain'
educationPlanDescriptors: 'Enrollment Domain'
educationalEnvironmentDescriptors: 'Cross-Domain'
electronicMailTypeDescriptors: 'Cross-Domain'
employmentStatusDescriptors: 'Staff Domain Domain'
entryGradeLevelReasonDescriptors: 'Enrollment Domain'
entryTypeDescriptors: 'Enrollment Domain'
eventCircumstanceDescriptors: 'Assessment Domain'
exitWithdrawTypeDescriptors: 'Enrollment Domain'
gradeLevelDescriptors: 'Cross-Domain'
gradePointAverageTypeDescriptors: 'Student Academic Record Domain'
gradeTypeDescriptors: 'Student Academic Record Domain'
gradebookEntryTypeDescriptors: 'Student Academic Record Domain'
gradingPeriodDescriptors: 'School Calendar Domain'
graduationPlanTypeDescriptors: 'Graduation Domain'
gunFreeSchoolsActReportingStatusDescriptors: 'Education Organization Domain'
homelessPrimaryNighttimeResidenceDescriptors: 'Alternative and Supplemental Services Domain'
homelessProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
identificationDocumentUseDescriptors: 'Staff Domain Domain'
incidentLocationDescriptors: 'Discipline Domain'
indicatorDescriptors: 'Education Organization Domain'
indicatorGroupDescriptors: 'Education Organization Domain'
indicatorLevelDescriptors: 'Education Organization Domain'
institutionTelephoneNumberTypeDescriptors: 'Education Organization Domain'
interactivityStyleDescriptors: 'Teaching and Learning Domain'
internetAccessDescriptors: 'Education Organization Domain'
interventionClassDescriptors: 'Intervention Domain'
interventionEffectivenessRatingDescriptors: 'Intervention Domain'
languageDescriptors: 'Cross-Domain'
languageInstructionProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
languageUseDescriptors: 'Cross-Domain'
learningStandardCategoryDescriptors: 'Assessment Domain'
learningStandardEquivalenceStrengthDescriptors: 'Assessment Domain'
learningStandardScopeDescriptors: 'Assessment Domain'
levelOfEducationDescriptors: 'Staff Domain Domain'
licenseStatusDescriptors: 'Education Organization Domain'
licenseTypeDescriptors: 'Education Organization Domain'
limitedEnglishProficiencyDescriptors: 'Student Identification and Demographics Domain'
localEducationAgencyCategoryDescriptors: 'Education Organization Domain'
localeDescriptors: 'Cross-Domain'
magnetSpecialProgramEmphasisSchoolDescriptors: 'Education Organization Domain'
mediumOfInstructionDescriptors: 'Teaching and Learning Domain'
methodCreditEarnedDescriptors: 'Student Academic Record Domain'
migrantEducationProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
monitoredDescriptors: 'Alternative and Supplemental Services Domain'
neglectedOrDelinquentProgramDescriptors: 'Alternative and Supplemental Services Domain'
neglectedOrDelinquentProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
networkPurposeDescriptors: 'Education Organization Domain'
oldEthnicityDescriptors: 'Student Identification and Demographics Domain'
operationalStatusDescriptors: 'Education Organization Domain'
otherNameTypeDescriptors: 'Student Identification and Demographics Domain'
participationDescriptors: 'Alternative and Supplemental Services Domain'
participationStatusDescriptors: 'Alternative and Supplemental Services Domain'
performanceBaseConversionDescriptors: 'Student Academic Record Domain'
performanceLevelDescriptors: 'Cross-Domain'
personalInformationVerificationDescriptors: 'Staff Domain Domain'
platformTypeDescriptors: 'Assessment Domain'
populationServedDescriptors: 'Intervention Domain'
postSecondaryEventCategoryDescriptors: 'Graduation Domain'
postSecondaryInstitutionLevelDescriptors: 'Education Organization Domain'
postingResultDescriptors: 'Staff Domain Domain'
proficiencyDescriptors: 'Alternative and Supplemental Services Domain'
programAssignmentDescriptors: 'Staff Domain Domain'
programCharacteristicDescriptors: 'Alternative and Supplemental Services Domain'
programSponsorDescriptors: 'Alternative and Supplemental Services Domain'
programTypeDescriptors: 'Alternative and Supplemental Services Domain'
progressDescriptors: 'Alternative and Supplemental Services Domain'
progressLevelDescriptors: 'Alternative and Supplemental Services Domain'
providerCategoryDescriptors: 'Education Organization Domain'
providerProfitabilityDescriptors: 'Education Organization Domain'
providerStatusDescriptors: 'Education Organization Domain'
publicationStatusDescriptors: 'Assessment Domain'
questionFormDescriptors: 'Survey Domain'
raceDescriptors: 'Cross-Domain'
reasonExitedDescriptors: 'Alternative and Supplemental Services Domain'
reasonNotTestedDescriptors: 'Student Academic Record Domain'
recognitionTypeDescriptors: 'Student Academic Record Domain'
relationDescriptors: 'Student Identification and Demographics Domain'
repeatIdentifierDescriptors: 'Teaching and Learning Domain'
reporterDescriptionDescriptors: 'Discipline Domain'
residencyStatusDescriptors: 'Enrollment Domain'
responseIndicatorDescriptors: 'Survey Domain'
responsibilityDescriptors: 'Enrollment Domain'
restraintEventReasonDescriptors: 'Discipline Domain'
resultDatatypeTypeDescriptors: 'Cross-Domain'
retestIndicatorDescriptors: 'Assessment Domain'
schoolCategoryDescriptors: 'Education Organization Domain'
schoolChoiceImplementStatusDescriptors: 'Education Organization Domain'
schoolFoodServiceProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
schoolTypeDescriptors: 'Education Organization Domain'
sectionCharacteristicDescriptors: 'Teaching and Learning Domain'
separationDescriptors: 'Staff Domain Domain'
separationReasonDescriptors: 'Staff Domain Domain'
serviceDescriptors: 'Alternative and Supplemental Services Domain'
sexDescriptors: 'Cross-Domain'
sourceSystemDescriptors: 'Cross-Domain'
specialEducationProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
specialEducationSettingDescriptors: 'Alternative and Supplemental Services Domain'
staffClassificationDescriptors: 'Staff Domain Domain'
staffIdentificationSystemDescriptors: 'Staff Domain Domain'
staffLeaveEventCategoryDescriptors: 'Staff Domain Domain'
stateAbbreviationDescriptors: 'Cross-Domain'
studentCharacteristicDescriptors: 'Student Identification and Demographics Domain'
studentIdentificationSystemDescriptors: 'Student Identification and Demographics Domain'
studentParticipationCodeDescriptors: 'Discipline Domain'
surveyCategoryDescriptors: 'Survey Domain'
surveyLevelDescriptors: 'Survey Domain'
teachingCredentialBasisDescriptors: 'Staff Domain Domain'
teachingCredentialDescriptors: 'Staff Domain Domain'
technicalSkillsAssessmentDescriptors: 'Alternative and Supplemental Services Domain'
telephoneNumberTypeDescriptors: 'Cross-Domain'
termDescriptors: 'School Calendar Domain'
titleIPartAParticipantDescriptors: 'Alternative and Supplemental Services Domain'
titleIPartAProgramServiceDescriptors: 'Alternative and Supplemental Services Domain'
titleIPartASchoolDesignationDescriptors: 'Education Organization Domain'
tribalAffiliationDescriptors: 'Cross-Domain'
visaDescriptors: 'Cross-Domain'
weaponDescriptors: 'Discipline Domain'
